name: Deploy Automático do Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Baixando os arquivos
        uses: actions/checkout@v4

      - name: Instalando o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Instalando dependências
        run: pnpm install

      - name: Compilando o site (Build)
        run: pnpm build

      - name: Jogando na vitrine (Deploy)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build